### ISSUE TITLE
The square...

### ISSUE THREAD

**Issue by th3m477** [chriswessels/meteor-glyphicons-halflings#1]
Hi,

Many (not all) of the icons seem to be coming through as the popular square (i.e. missing character in font file). CSS looks correct.

Have you checked font file is correct which is included? Otherwise I can update and do pull request if needed.

Thanks!
Matt

**Comment by chriswessels** [comment]
Hey @th3m477,

This was working fine when I last checked, but it has been a while!

If you're looking into it already and could submit a pull request, that would be appreciated.

Thanks,
Chris

**Comment by th3m477** [comment]
File is fine; double checked encoding, was my default build config.

**Comment by chriswessels** [comment]
I see, thanks @th3m477.
